/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminTenantsTenantIdMembershipsRouteImport } from './routes/admin/tenants.$tenantId.memberships'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsTenantIdMembershipsRoute =
  AdminTenantsTenantIdMembershipsRouteImport.update({
    id: '/$tenantId/memberships',
    path: '/$tenantId/memberships',
    getParentRoute: () => AdminTenantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/tenants/$tenantId/memberships': typeof AdminTenantsTenantIdMembershipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/tenants/$tenantId/memberships': typeof AdminTenantsTenantIdMembershipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/tenants/$tenantId/memberships': typeof AdminTenantsTenantIdMembershipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/tenants'
    | '/admin/tenants/$tenantId/memberships'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/tenants'
    | '/admin/tenants/$tenantId/memberships'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/tenants'
    | '/admin/tenants/$tenantId/memberships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$tenantId/memberships': {
      id: '/admin/tenants/$tenantId/memberships'
      path: '/$tenantId/memberships'
      fullPath: '/admin/tenants/$tenantId/memberships'
      preLoaderRoute: typeof AdminTenantsTenantIdMembershipsRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
  }
}

interface AdminTenantsRouteChildren {
  AdminTenantsTenantIdMembershipsRoute: typeof AdminTenantsTenantIdMembershipsRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsTenantIdMembershipsRoute: AdminTenantsTenantIdMembershipsRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
