/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClubRouteImport } from './routes/club'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubIndexRouteImport } from './routes/club/index'
import { Route as ClubLoginRouteImport } from './routes/club_.login'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminTenantsTenantIdMembershipsRouteImport } from './routes/admin/tenants.$tenantId.memberships'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubLoginRoute = ClubLoginRouteImport.update({
  id: '/club_/login',
  path: '/club/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsTenantIdMembershipsRoute =
  AdminTenantsTenantIdMembershipsRouteImport.update({
    id: '/$tenantId/memberships',
    path: '/$tenantId/memberships',
    getParentRoute: () => AdminTenantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/club': typeof ClubRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/club/login': typeof ClubLoginRoute
  '/club/': typeof ClubIndexRoute
  '/admin/tenants/$tenantId/memberships': typeof AdminTenantsTenantIdMembershipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/club/login': typeof ClubLoginRoute
  '/club': typeof ClubIndexRoute
  '/admin/tenants/$tenantId/memberships': typeof AdminTenantsTenantIdMembershipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/club': typeof ClubRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/club_/login': typeof ClubLoginRoute
  '/club/': typeof ClubIndexRoute
  '/admin/tenants/$tenantId/memberships': typeof AdminTenantsTenantIdMembershipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/club'
    | '/login'
    | '/admin/tenants'
    | '/club/login'
    | '/club/'
    | '/admin/tenants/$tenantId/memberships'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/tenants'
    | '/club/login'
    | '/club'
    | '/admin/tenants/$tenantId/memberships'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/club'
    | '/login'
    | '/admin/tenants'
    | '/club_/login'
    | '/club/'
    | '/admin/tenants/$tenantId/memberships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClubRoute: typeof ClubRouteWithChildren
  LoginRoute: typeof LoginRoute
  ClubLoginRoute: typeof ClubLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club_/login': {
      id: '/club_/login'
      path: '/club/login'
      fullPath: '/club/login'
      preLoaderRoute: typeof ClubLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$tenantId/memberships': {
      id: '/admin/tenants/$tenantId/memberships'
      path: '/$tenantId/memberships'
      fullPath: '/admin/tenants/$tenantId/memberships'
      preLoaderRoute: typeof AdminTenantsTenantIdMembershipsRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
  }
}

interface AdminTenantsRouteChildren {
  AdminTenantsTenantIdMembershipsRoute: typeof AdminTenantsTenantIdMembershipsRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsTenantIdMembershipsRoute: AdminTenantsTenantIdMembershipsRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClubRouteChildren {
  ClubIndexRoute: typeof ClubIndexRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubIndexRoute: ClubIndexRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClubRoute: ClubRouteWithChildren,
  LoginRoute: LoginRoute,
  ClubLoginRoute: ClubLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
